#pragma once

#define VIAL_KEYBOARD_UID {0x45, 0xEE, 0xB2, 0xB2, 0xFE, 0x38, 0xF4, 0x4D}
#define VIAL_UNLOCK_COMBO_ROWS {0,9}
#define VIAL_UNLOCK_COMBO_COLS {0,5}

#define DYNAMIC_KEYMAP_LAYER_COUNT 8
#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 4
#define QUICK_TAP_TERM_PER_KEY
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_LED_STATE_ENABLE
#define SPLIT_MODS_ENABLE

#define LEADER_TIMEOUT 300
#define LEADER_NO_TIMEOUT
#define LEADER_PER_KEY_TIMING
